Author: Tristan Thordarson

Date:

Project: 05

Acknowledgements: 

# Deep learning with PyTorch: A 60 minute Blitz 
[Tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

One of the most popular and widely used deep learning framework

Fast, flexible and seamless

Built to use the power of GPUs for faster training

## Part 1: Tensors


In [1]:
import torch
import numpy as np

### Tensor Initialization

In [6]:
# Directly from data
data = [[1,2],[1,2]]
x_data = torch.tensor(data)

# From NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

#With random or constant values
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1498, 0.5149],
        [0.2484, 0.3933]]) 

Random Tensor: 
 tensor([[0.0234, 0.2451, 0.3713],
        [0.9811, 0.7620, 0.7051]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor attributes

 In general, torch.tensor is preferred over torch.Tensor when creating tensors in PyTorch.

In [8]:
tensor = torch.rand(3,4)
print(f"Shape of a tensor: {tensor.shape}")
print(f"Datatype of a tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of a tensor: torch.Size([3, 4])
Datatype of a tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operations

In [10]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")
else:
  print("Not available")

Not available


In [31]:
# Standard numpy-like indexing and slicing:

tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

# Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1) 
# dim=0 means concatenation along the first dimension (stacking the tensors along the rows, increasing the number of rows).
# dim=1 means concatenation along the second dimension (stacking the tensors along the columns, increasing the number of columns).

print(t1)

# Multiplying tensors
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")


# This computes the matrix multiplication between two tensors
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

print(f"Alternative: \n {torch.matmul(tensor,tensor)}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
Alternative: 
 tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])


In [46]:
import torch
import time

# Create two random tensors for matrix multiplication
tensor = torch.rand(1000, 1000)

# Measure time for tensor.matmul(tensor.T)
start_time = time.time()
result1 = tensor.matmul(tensor.T)
end_time = time.time()
print(f"tensor.matmul(tensor.T) took {end_time - start_time:.6f} seconds")

# Measure time for tensor @ tensor.T
start_time = time.time()
result2 = tensor @ tensor.T
end_time = time.time()
print(f"tensor @ tensor.T took {end_time - start_time:.6f} seconds")

# Measure time for torch.matmul(tensor, tensor.T)
start_time = time.time()
result3 = torch.matmul(tensor, tensor.T)
end_time = time.time()
print(f"torch.matmul(tensor, tensor.T) took {end_time - start_time:.6f} seconds")


tensor.matmul(tensor.T) took 0.007862 seconds
tensor @ tensor.T took 0.003520 seconds
torch.matmul(tensor, tensor.T) took 0.002918 seconds


In [49]:
# In-place operations
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor,"\n")
tensor.add(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
